# docker-compose.yml
version: "3.5"

services:
  node:
    container_name: node_api
    image: node:10.16.3-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - MONGODB_URI=mongodb://user:pwd@mongo:27017/todoapp
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    depends_on:
      - mongo
    networks:
      - kata-network
      - kata-api-network
  mongo:
    container_name: mongo
    image: mongo:4.2
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: todoapp
    networks:
      - kata-api-network
networks:
  kata-network:
    name: kata-network
  kata-api-network:
